apiVersion: v1
kind: Pod
metadata:
  name: kube-controller-manager
spec:
  containers:
  - image: gcr.io/google_containers/hyperkube:v1.5.5
    command:
    - /hyperkube
    - controller-manager
    - --master=127.0.0.1:8080
    - --service-cluster-ip-range=172.16.0.0/16
    - --root-ca-file=/etc/kubernetes/pki/ca.pem
    - --service-account-private-key-file=/etc/kubernetes/pki/apiserver-key.pem
    - --cluster-signing-cert-file=/etc/kubernetes/pki/ca.pem
    - --cluster-signing-key-file=/etc/kubernetes/pki/ca-key.pem
    - --insecure-experimental-approve-all-kubelet-csrs-for-group=system:kubelet-bootstrap
    - --leader-elect=true
    - --logtostderr=true
    livenessProbe:
      httpGet:
        path: /healthz
        port: 10252
      initialDelaySeconds: 15
      timeoutSeconds: 1
    name: kube-controller-manager
    volumeMounts:
    - mountPath: /etc/kubernetes
      name: etckube
      readOnly: true
    - mountPath: /etc/ssl
      name: etcssl
      readOnly: true
  hostNetwork: true
  volumes:
  - hostPath:
      path: /etc/kubernetes
    name: etckube
  - hostPath:
      path: /etc/ssl
    name: etcssl
